// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace pedidos.Migrations
{
    [DbContext(typeof(OrdersDishDb))]
    partial class OrdersDishDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dish", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("description")
                        .HasMaxLength(170)
                        .HasColumnType("varchar(170)");

                    b.Property<string>("img")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<float?>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<float?>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("IngredientDish", b =>
                {
                    b.Property<int?>("ingredientId")
                        .HasColumnType("int");

                    b.Property<int?>("dishId")
                        .HasColumnType("int");

                    b.HasKey("ingredientId", "dishId");

                    b.ToTable("ingredientDishes");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("id"));

                    b.Property<float?>("count")
                        .HasColumnType("float");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dishesOrded")
                        .HasColumnType("longtext");

                    b.Property<string>("nameCustomer")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("id");

                    b.ToTable("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
